name: sim2real

dependencies:
    - python==3.6.8
    - tensorflow==1.14.0
    - pip:
        - numpy==1.17.1
        - gym==0.14.0
        - ray==0.7.4
        - lz4==2.2.1
        - psutil==5.6.3
        - requests==2.22.0
        - matplotlib==3.0.0
        - scikit-image==0.15.0
        - gym==0.14.0
        - awscli
